# Generated by Django 3.1.2 on 2021-01-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.state', verbose_name='State')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile', verbose_name='Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.state', verbose_name='State')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('img', models.ImageField(upload_to='transaction')),
                ('bank_account_receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to='transaction.bank_account', verbose_name='Receiver')),
                ('bank_account_sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Sender', to='transaction.bank_account', verbose_name='Sender')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.currency', verbose_name='Currency')),
                ('transaction_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.state', verbose_name='State')),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.type', verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.country', verbose_name='Country')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.state', verbose_name='State')),
            ],
        ),
    ]
